# =====================================================
# LOCAL DATABASE
# =====================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/lastkey_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =====================================================
# LOCAL JWT
# =====================================================

JWT_SECRET=${JWT_SECRET}

# =====================================================
# LOCAL BREVO SMTP
# =====================================================

MAIL_USERNAME=${MAIL_USERNAME}
MAIL_PASSWORD=${MAIL_PASSWORD}

MAIL_FROM=pandeytrayambak1519@gmail.com

# =====================================================
# LOCAL DOCUMENT ENCRYPTION
# =====================================================

ENCRYPTION_KEY=${ENCRYPTION_KEY}

# =====================================================
# LOCAL FILE STORAGE
# =====================================================

FILE_UPLOAD_DIR=storage/documents
PROFILE_IMAGES_DIR=uploads/profile-images
PROFILE_IMAGES_URL=http://localhost:8080/uploads/profile-images

# =====================================================
# LOCAL CORS
# =====================================================

CORS_ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000

# =====================================================
# LOCAL SWAGGER
# =====================================================

SWAGGER_ENABLED=true

# =====================================================
# LOCAL ACTUATOR
# =====================================================

management.endpoint.health.show-details=always

# =====================================================
# LOCAL LOGGING
# =====================================================

SHOW_SQL=true

logging.level.com.lastkey.backend=DEBUG
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.boot.autoconfigure.mail=DEBUG

spring.mail.properties.mail.debug=true