package com.lastkey.backend.notification.enums;

public enum NotificationType {

    DOCUMENT_UPLOADED,
    DOCUMENT_UPDATED,
    DOCUMENT_DELETED,
    DOCUMENT_EXPIRY_REMINDER,
    DOCUMENT_EXPIRED,

    CATEGORY_CREATED,
    CATEGORY_UPDATED,
    CATEGORY_DELETED,

    NOMINEE_ADDED,
    NOMINEE_UPDATED,
    NOMINEE_REMOVED,

    NOMINEE_DOCUMENT_ASSIGNED,
    NOMINEE_DOCUMENT_ACCESS_UPDATED,
    NOMINEE_DOCUMENT_ACCESS_REMOVED,

    EMERGENCY_REQUEST_CREATED,
    EMERGENCY_REQUEST_UPDATED,
    EMERGENCY_CANCELLED,
    EMERGENCY_APPROVED,
    EMERGENCY_REJECTED,

    DOCUMENT_RELEASED,
  
    DOCUMENT_ACCESS_REVOKED,

    SYSTEM
}